# Generated by Django 4.1 on 2022-08-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myPic', models.ImageField(upload_to='articles/')),
                ('myName', models.CharField(max_length=80)),
                ('mySurname', models.CharField(max_length=80)),
                ('my_location', models.CharField(max_length=200)),
                ('html_status', models.IntegerField(default=50)),
                ('css_status', models.IntegerField(default=50)),
                ('js_status', models.IntegerField(default=50)),
                ('python_status', models.IntegerField(default=50)),
                ('django_status', models.IntegerField(default=50)),
                ('react_status', models.IntegerField(default=50)),
                ('birthday', models.CharField(max_length=100)),
                ('myPhone_number', models.CharField(max_length=50)),
                ('now_city', models.CharField(max_length=100)),
                ('my_age', models.CharField(max_length=20)),
                ('my_email', models.CharField(max_length=100)),
                ('freelance_status', models.CharField(max_length=50)),
                ('about_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Web Site', 'Web'), ('Telegram Bot', 'TgBot')], max_length=100)),
                ('category_2', models.CharField(choices=[('Web', 'Web'), ('TgBot', 'TgBot')], max_length=100, null=True)),
                ('client', models.CharField(max_length=50)),
                ('image_1', models.ImageField(null=True, upload_to='articles/')),
                ('image_2', models.ImageField(null=True, upload_to='articles/')),
                ('project_date', models.DateTimeField(auto_now_add=True)),
                ('project_url', models.CharField(max_length=100)),
                ('about_project', models.TextField()),
            ],
        ),
    ]
