# Generated by Django 4.1 on 2022-08-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_title_alter_portfolio_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfoconfig',
            name='bootstrap_status',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='myinfoconfig',
            name='sql_status',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='myinfoconfig',
            name='tgbot_status',
            field=models.IntegerField(default=50),
        ),
    ]
