# Generated by Django 4.1 on 2022-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_myinfoconfig_bootstrap_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfoconfig',
            name='myCv',
            field=models.FileField(null=True, upload_to='docs/'),
        ),
    ]
